package com.david.entity.h2;
// Generated 2018-5-29 1:37:44 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * BatchJobInstance generated by hbm2java
 */
public class BatchJobInstance implements java.io.Serializable {

	private Long jobInstanceId;
	private Long version;
	private String jobName;
	private String jobKey;
	private Set batchJobExecutions = new HashSet(0);

	public BatchJobInstance() {
	}

	public BatchJobInstance(String jobName, String jobKey) {
		this.jobName = jobName;
		this.jobKey = jobKey;
	}

	public BatchJobInstance(String jobName, String jobKey, Set batchJobExecutions) {
		this.jobName = jobName;
		this.jobKey = jobKey;
		this.batchJobExecutions = batchJobExecutions;
	}

	public Long getJobInstanceId() {
		return this.jobInstanceId;
	}

	public void setJobInstanceId(Long jobInstanceId) {
		this.jobInstanceId = jobInstanceId;
	}

	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	public String getJobKey() {
		return this.jobKey;
	}

	public void setJobKey(String jobKey) {
		this.jobKey = jobKey;
	}

	public Set getBatchJobExecutions() {
		return this.batchJobExecutions;
	}

	public void setBatchJobExecutions(Set batchJobExecutions) {
		this.batchJobExecutions = batchJobExecutions;
	}

}
