package com.david.entity.h2;
// Generated 2018-5-29 1:37:44 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * BatchStepExecution generated by hbm2java
 */
public class BatchStepExecution implements java.io.Serializable {

	private Long stepExecutionId;
	private long version;
	private BatchJobExecution batchJobExecution;
	private String stepName;
	private Date startTime;
	private Date endTime;
	private String status;
	private Long commitCount;
	private Long readCount;
	private Long filterCount;
	private Long writeCount;
	private Long readSkipCount;
	private Long writeSkipCount;
	private Long processSkipCount;
	private Long rollbackCount;
	private String exitCode;
	private String exitMessage;
	private Date lastUpdated;
	private BatchStepExecutionContext batchStepExecutionContext;

	public BatchStepExecution() {
	}

	public BatchStepExecution(BatchJobExecution batchJobExecution, String stepName, Date startTime) {
		this.batchJobExecution = batchJobExecution;
		this.stepName = stepName;
		this.startTime = startTime;
	}

	public BatchStepExecution(BatchJobExecution batchJobExecution, String stepName, Date startTime, Date endTime,
			String status, Long commitCount, Long readCount, Long filterCount, Long writeCount, Long readSkipCount,
			Long writeSkipCount, Long processSkipCount, Long rollbackCount, String exitCode, String exitMessage,
			Date lastUpdated, BatchStepExecutionContext batchStepExecutionContext) {
		this.batchJobExecution = batchJobExecution;
		this.stepName = stepName;
		this.startTime = startTime;
		this.endTime = endTime;
		this.status = status;
		this.commitCount = commitCount;
		this.readCount = readCount;
		this.filterCount = filterCount;
		this.writeCount = writeCount;
		this.readSkipCount = readSkipCount;
		this.writeSkipCount = writeSkipCount;
		this.processSkipCount = processSkipCount;
		this.rollbackCount = rollbackCount;
		this.exitCode = exitCode;
		this.exitMessage = exitMessage;
		this.lastUpdated = lastUpdated;
		this.batchStepExecutionContext = batchStepExecutionContext;
	}

	public Long getStepExecutionId() {
		return this.stepExecutionId;
	}

	public void setStepExecutionId(Long stepExecutionId) {
		this.stepExecutionId = stepExecutionId;
	}

	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	public BatchJobExecution getBatchJobExecution() {
		return this.batchJobExecution;
	}

	public void setBatchJobExecution(BatchJobExecution batchJobExecution) {
		this.batchJobExecution = batchJobExecution;
	}

	public String getStepName() {
		return this.stepName;
	}

	public void setStepName(String stepName) {
		this.stepName = stepName;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Long getCommitCount() {
		return this.commitCount;
	}

	public void setCommitCount(Long commitCount) {
		this.commitCount = commitCount;
	}

	public Long getReadCount() {
		return this.readCount;
	}

	public void setReadCount(Long readCount) {
		this.readCount = readCount;
	}

	public Long getFilterCount() {
		return this.filterCount;
	}

	public void setFilterCount(Long filterCount) {
		this.filterCount = filterCount;
	}

	public Long getWriteCount() {
		return this.writeCount;
	}

	public void setWriteCount(Long writeCount) {
		this.writeCount = writeCount;
	}

	public Long getReadSkipCount() {
		return this.readSkipCount;
	}

	public void setReadSkipCount(Long readSkipCount) {
		this.readSkipCount = readSkipCount;
	}

	public Long getWriteSkipCount() {
		return this.writeSkipCount;
	}

	public void setWriteSkipCount(Long writeSkipCount) {
		this.writeSkipCount = writeSkipCount;
	}

	public Long getProcessSkipCount() {
		return this.processSkipCount;
	}

	public void setProcessSkipCount(Long processSkipCount) {
		this.processSkipCount = processSkipCount;
	}

	public Long getRollbackCount() {
		return this.rollbackCount;
	}

	public void setRollbackCount(Long rollbackCount) {
		this.rollbackCount = rollbackCount;
	}

	public String getExitCode() {
		return this.exitCode;
	}

	public void setExitCode(String exitCode) {
		this.exitCode = exitCode;
	}

	public String getExitMessage() {
		return this.exitMessage;
	}

	public void setExitMessage(String exitMessage) {
		this.exitMessage = exitMessage;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public BatchStepExecutionContext getBatchStepExecutionContext() {
		return this.batchStepExecutionContext;
	}

	public void setBatchStepExecutionContext(BatchStepExecutionContext batchStepExecutionContext) {
		this.batchStepExecutionContext = batchStepExecutionContext;
	}

}
