package com.david.entity.h2;
// Generated 2018-5-29 1:37:44 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BatchJobExecution generated by hbm2java
 */
public class BatchJobExecution implements java.io.Serializable {

	private Long jobExecutionId;
	private Long version;
	private BatchJobInstance batchJobInstance;
	private Date createTime;
	private Date startTime;
	private Date endTime;
	private String status;
	private String exitCode;
	private String exitMessage;
	private Date lastUpdated;
	private String jobConfigurationLocation;
	private Set batchStepExecutions = new HashSet(0);
	private Set batchJobExecutionParamses = new HashSet(0);
	private BatchJobExecutionContext batchJobExecutionContext;

	public BatchJobExecution() {
	}

	public BatchJobExecution(BatchJobInstance batchJobInstance, Date createTime) {
		this.batchJobInstance = batchJobInstance;
		this.createTime = createTime;
	}

	public BatchJobExecution(BatchJobInstance batchJobInstance, Date createTime, Date startTime, Date endTime,
			String status, String exitCode, String exitMessage, Date lastUpdated, String jobConfigurationLocation,
			Set batchStepExecutions, Set batchJobExecutionParamses, BatchJobExecutionContext batchJobExecutionContext) {
		this.batchJobInstance = batchJobInstance;
		this.createTime = createTime;
		this.startTime = startTime;
		this.endTime = endTime;
		this.status = status;
		this.exitCode = exitCode;
		this.exitMessage = exitMessage;
		this.lastUpdated = lastUpdated;
		this.jobConfigurationLocation = jobConfigurationLocation;
		this.batchStepExecutions = batchStepExecutions;
		this.batchJobExecutionParamses = batchJobExecutionParamses;
		this.batchJobExecutionContext = batchJobExecutionContext;
	}

	public Long getJobExecutionId() {
		return this.jobExecutionId;
	}

	public void setJobExecutionId(Long jobExecutionId) {
		this.jobExecutionId = jobExecutionId;
	}

	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public BatchJobInstance getBatchJobInstance() {
		return this.batchJobInstance;
	}

	public void setBatchJobInstance(BatchJobInstance batchJobInstance) {
		this.batchJobInstance = batchJobInstance;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getExitCode() {
		return this.exitCode;
	}

	public void setExitCode(String exitCode) {
		this.exitCode = exitCode;
	}

	public String getExitMessage() {
		return this.exitMessage;
	}

	public void setExitMessage(String exitMessage) {
		this.exitMessage = exitMessage;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getJobConfigurationLocation() {
		return this.jobConfigurationLocation;
	}

	public void setJobConfigurationLocation(String jobConfigurationLocation) {
		this.jobConfigurationLocation = jobConfigurationLocation;
	}

	public Set getBatchStepExecutions() {
		return this.batchStepExecutions;
	}

	public void setBatchStepExecutions(Set batchStepExecutions) {
		this.batchStepExecutions = batchStepExecutions;
	}

	public Set getBatchJobExecutionParamses() {
		return this.batchJobExecutionParamses;
	}

	public void setBatchJobExecutionParamses(Set batchJobExecutionParamses) {
		this.batchJobExecutionParamses = batchJobExecutionParamses;
	}

	public BatchJobExecutionContext getBatchJobExecutionContext() {
		return this.batchJobExecutionContext;
	}

	public void setBatchJobExecutionContext(BatchJobExecutionContext batchJobExecutionContext) {
		this.batchJobExecutionContext = batchJobExecutionContext;
	}

}
