package com.david.entity.h2;
// Generated 2018-5-29 1:37:44 by Hibernate Tools 5.3.0.Beta2

/**
 * BatchStepExecutionContext generated by hbm2java
 */
public class BatchStepExecutionContext implements java.io.Serializable {

	private long stepExecutionId;
	private BatchStepExecution batchStepExecution;
	private String shortContext;
	private String serializedContext;

	public BatchStepExecutionContext() {
	}

	public BatchStepExecutionContext(BatchStepExecution batchStepExecution, String shortContext) {
		this.batchStepExecution = batchStepExecution;
		this.shortContext = shortContext;
	}

	public BatchStepExecutionContext(BatchStepExecution batchStepExecution, String shortContext,
			String serializedContext) {
		this.batchStepExecution = batchStepExecution;
		this.shortContext = shortContext;
		this.serializedContext = serializedContext;
	}

	public long getStepExecutionId() {
		return this.stepExecutionId;
	}

	public void setStepExecutionId(long stepExecutionId) {
		this.stepExecutionId = stepExecutionId;
	}

	public BatchStepExecution getBatchStepExecution() {
		return this.batchStepExecution;
	}

	public void setBatchStepExecution(BatchStepExecution batchStepExecution) {
		this.batchStepExecution = batchStepExecution;
	}

	public String getShortContext() {
		return this.shortContext;
	}

	public void setShortContext(String shortContext) {
		this.shortContext = shortContext;
	}

	public String getSerializedContext() {
		return this.serializedContext;
	}

	public void setSerializedContext(String serializedContext) {
		this.serializedContext = serializedContext;
	}

}
